apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  type: ClusterIP
  selector:
    app: pythonapp
  ports: 
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pythonapp
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: gcr.io/lbg-python-cohort-8/automated-image:latest
        ports:
        - containerPort: 8080
