apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  type: ClusterIP
  selector:
    app: pythonapp
  ports: 
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnpythonapp
  labels:
    app: mnpythonapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mnpythonapp
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mnpythonapp
    spec:
      containers:
      - name: mnpythonapp
        image: gcr.io/lbg-python-cohort-8/mnpythonapp:latest
        ports:
        - containerPort: 8080
